# Generated by Django 5.2.7 on 2025-11-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomclt', models.CharField(max_length=40)),
                ('prenomclt', models.CharField(max_length=60)),
                ('adresseclt', models.CharField(max_length=60)),
                ('telclt', models.CharField(max_length=25)),
                ('emailclt', models.EmailField(max_length=70)),
                ('photoclt', models.ImageField(blank=True, null=True, upload_to='Clients/')),
                ('date_saisie', models.DateField(auto_now=True)),
            ],
            options={
                'unique_together': {('nomclt', 'prenomclt')},
            },
        ),
    ]
