# Generated by Django 5.2.7 on 2025-12-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0002_alter_clients_emailclt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='prenomclt',
            new_name='nom_complet',
        ),
        migrations.AlterUniqueTogether(
            name='clients',
            unique_together={('nom_complet', 'telclt')},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='emailclt',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='nomclt',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='photoclt',
        ),
    ]
