# Generated by Django 5.2.7 on 2025-12-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date_notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='destinataire',
            field=models.EmailField(blank=True, help_text='Utilisateur destinataire de la notification.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='destinataire_email',
            field=models.EmailField(blank=True, help_text='Email du parent ou tuteur si non utilisateur.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
