# Generated by Django 5.2.7 on 2025-12-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_notifications', '0002_remove_notification_date_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='destinataire_email',
            field=models.EmailField(blank=True, help_text='Email du client ou tuteur si non utilisateur.', max_length=254, null=True),
        ),
    ]
