# Generated by Django 5.2.7 on 2025-12-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entrepriese', models.CharField(max_length=80)),
                ('contact1', models.CharField(max_length=30)),
                ('contact2', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
