# Generated by Django 5.2.7 on 2025-12-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
