# Generated by Django 5.2.7 on 2025-12-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_entreprise', '0002_entreprise_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='date_maj',
            field=models.DateField(auto_now=True),
        ),
    ]
