# Generated by Django 5.2.7 on 2025-12-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_entreprise', '0003_entreprise_date_maj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='Entreprise/'),
        ),
    ]
