# Generated by Django 5.2.7 on 2025-12-22 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_entreprise', '0005_entrepot_magasin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=45)),
                ('date_operation', models.DateField(auto_now_add=True)),
                ('quantite', models.PositiveIntegerField()),
                ('pu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('designation', models.CharField(max_length=105)),
                ('provient_de', models.CharField(max_length=45)),
                ('destine_a', models.CharField(max_length=45)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
