# Generated by Django 5.2.7 on 2025-12-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_entreprise', '0006_depenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenses',
            name='provient_de',
        ),
        migrations.RemoveField(
            model_name='depenses',
            name='pu',
        ),
        migrations.RemoveField(
            model_name='depenses',
            name='quantite',
        ),
    ]
