# Generated by Django 5.2.7 on 2025-12-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_entreprise', '0007_remove_depenses_provient_de_remove_depenses_pu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depenses',
            name='type_operation',
        ),
    ]
