# Generated by Django 5.2.7 on 2025-12-11 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('type', models.CharField(choices=[('Inscriptions', 'Inscriptions'), ('Réinscription', 'Réinscription'), ('Paiements', 'Paiements'), ('Personnel', 'Personnel')], max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
