# Generated by Django 5.2.7 on 2025-12-15 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desgcategorie', models.CharField(max_length=65)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_maj', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refprod', models.CharField(max_length=50)),
                ('desgprod', models.TextField(blank=True, null=True)),
                ('qtestock', models.IntegerField(default=0)),
                ('seuil', models.IntegerField(default=0)),
                ('pu', models.IntegerField(default=0)),
                ('prix_en_gros', models.IntegerField(default=0)),
                ('photoprod', models.ImageField(blank=True, null=True, upload_to='Produits/')),
                ('date_maj', models.DateField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='gestion_produits.categorieproduit')),
            ],
            options={
                'unique_together': {('refprod', 'categorie')},
            },
        ),
        migrations.CreateModel(
            name='LivraisonsProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtelivrer', models.IntegerField(default=0)),
                ('datelivrer', models.DateField(auto_now=True)),
                ('statuts', models.CharField(max_length=60, null=True)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.produits')),
            ],
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcmd', models.CharField(max_length=60)),
                ('qtecmd', models.IntegerField(default=0)),
                ('datecmd', models.DateField(auto_now=True)),
                ('nom_complet_fournisseur', models.CharField(max_length=60, null=True)),
                ('adresse_fournisseur', models.CharField(max_length=60, null=True)),
                ('telephone_fournisseur', models.CharField(max_length=25, null=True)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.produits')),
            ],
        ),
        migrations.CreateModel(
            name='VenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('nom_complet_client', models.CharField(max_length=60, null=True)),
                ('adresseclt_client', models.CharField(max_length=60, null=True)),
                ('telclt_client', models.CharField(max_length=25, null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('prix', models.IntegerField(default=0)),
                ('montant_reduction', models.IntegerField(default=0)),
                ('sous_total', models.IntegerField(default=0)),
                ('date_saisie', models.DateField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion_produits.produits')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion_produits.venteproduit')),
            ],
        ),
    ]
