# Generated by Django 5.2.7 on 2025-11-02 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_clients', '0001_initial'),
        ('gestion_fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desgcategorie', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refprod', models.CharField(max_length=30)),
                ('desgprod', models.CharField(max_length=60)),
                ('qtestock', models.IntegerField(default=0)),
                ('seuil', models.IntegerField(default=0)),
                ('pu', models.IntegerField(default=0)),
                ('photoprod', models.ImageField(blank=True, null=True, upload_to='Produits/')),
                ('date_maj', models.DateField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.categorieproduit')),
            ],
            options={
                'unique_together': {('refprod',)},
            },
        ),
        migrations.CreateModel(
            name='Livraisons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtelivrer', models.IntegerField(default=0)),
                ('datelivrer', models.DateField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_fournisseurs.fournisseurs')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.produits')),
            ],
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcmd', models.CharField(max_length=40)),
                ('qtecmd', models.IntegerField(default=0)),
                ('datecmd', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clients.clients')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.produits')),
            ],
        ),
    ]
