# Generated by Django 5.2.7 on 2025-12-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='date_saisie',
            field=models.DateField(auto_now_add=True),
        ),
    ]
