# Generated by Django 5.2.7 on 2025-11-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieproduit',
            name='date_maj',
            field=models.DateField(auto_now=True),
        ),
    ]
