# Generated by Django 5.2.7 on 2025-12-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='adresse_fournisseur',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commandes',
            name='nom_complet_fournisseur',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commandes',
            name='telephone_fournisseur',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
