# Generated by Django 5.2.7 on 2025-12-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduit',
            name='date_maj',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
