# Generated by Django 5.2.7 on 2025-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0002_alter_lignevente_date_saisie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='datecmd',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livraisonsproduits',
            name='datelivrer',
            field=models.DateField(auto_now_add=True),
        ),
    ]
