# Generated by Django 5.2.7 on 2025-12-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0002_categorieproduit_date_maj'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produits',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categorieproduit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorieproduit',
            name='desgcategorie',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='produits',
            name='desgprod',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='refprod',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='produits',
            unique_together={('refprod', 'categorie')},
        ),
    ]
