# Generated by Django 5.2.7 on 2025-12-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0002_alter_stockproduit_date_maj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='statuts',
            field=models.CharField(default='Non Livrer', max_length=60, null=True),
        ),
    ]
