# Generated by Django 5.2.7 on 2025-12-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0003_alter_produits_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='numcmd',
            field=models.CharField(max_length=60),
        ),
    ]
