# Generated by Django 5.2.7 on 2025-12-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0003_alter_commandes_datecmd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraisonsproduits',
            name='numlivrer',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='nom_complet_fournisseur',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='telephone_fournisseur',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='nom_complet_client',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='telclt_client',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
