# Generated by Django 5.2.7 on 2025-12-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0003_alter_commandes_statuts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venteproduit',
            options={'ordering': ['-code']},
        ),
        migrations.DeleteModel(
            name='MouvementProduit',
        ),
    ]
