# Generated by Django 5.2.7 on 2025-12-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0004_alter_venteproduit_options_delete_mouvementproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='benefice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='benefice_total',
            field=models.IntegerField(default=0),
        ),
    ]
