# Generated by Django 5.2.7 on 2025-12-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0004_livraisonsproduits_numlivrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='statuts',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
