# Generated by Django 5.2.7 on 2025-12-11 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0004_alter_commandes_numcmd'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentesProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vente', models.IntegerField(default=0)),
                ('date_vente', models.DateField(auto_now=True)),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.categorieproduit')),
            ],
        ),
    ]
