# Generated by Django 5.2.7 on 2025-12-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0005_ventesproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('prix', models.IntegerField(default=0)),
                ('sous_total', models.IntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.produits')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.venteproduit')),
            ],
        ),
        migrations.DeleteModel(
            name='VentesProduit',
        ),
    ]
