# Generated by Django 5.2.7 on 2025-12-15 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0005_commandes_statuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraisonsproduits',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_produits.commandes'),
        ),
    ]
