# Generated by Django 5.2.7 on 2025-12-11 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0006_venteproduit_lignevente_delete_ventesproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='adresseclt_client',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='date_saisie',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='nom_complet_client',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='telclt_client',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion_produits.venteproduit'),
        ),
    ]
