# Generated by Django 5.2.7 on 2025-12-23 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0006_historicalcommandes_historicallivraisonsproduits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstockproduit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Stock Produit', 'verbose_name_plural': 'historical Stocks Produits'},
        ),
        migrations.AlterModelOptions(
            name='stockproduit',
            options={'verbose_name': 'Stock Produit', 'verbose_name_plural': 'Stocks Produits'},
        ),
        migrations.RemoveConstraint(
            model_name='stockproduit',
            name='stock_entrepot_ou_magasin',
        ),
        migrations.RemoveConstraint(
            model_name='stockproduit',
            name='unique_stock_produit_lieu',
        ),
        migrations.RemoveField(
            model_name='historicalstockproduit',
            name='entrepot',
        ),
        migrations.RemoveField(
            model_name='historicalstockproduit',
            name='magasin',
        ),
        migrations.RemoveField(
            model_name='stockproduit',
            name='entrepot',
        ),
        migrations.RemoveField(
            model_name='stockproduit',
            name='magasin',
        ),
        migrations.AlterField(
            model_name='stockproduit',
            name='date_maj',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockproduit',
            name='produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='gestion_produits.produits'),
        ),
    ]
