# Generated by Django 5.2.7 on 2025-12-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0007_alter_historicalstockproduit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduit',
            name='produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gestion_produits.produits'),
        ),
    ]
