# Generated by Django 5.2.7 on 2025-12-12 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0007_lignevente_adresseclt_client_lignevente_date_saisie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion_produits.produits'),
        ),
    ]
