# Generated by Django 5.2.7 on 2025-12-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0008_alter_lignevente_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes',
            name='client',
        ),
    ]
