# Generated by Django 5.2.7 on 2025-12-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0008_alter_stockproduit_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='pu_reduction',
            field=models.IntegerField(default=0),
        ),
    ]
