# Generated by Django 5.2.7 on 2025-12-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0009_remove_commandes_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='gestion_produits.categorieproduit'),
        ),
    ]
