# Generated by Django 5.2.7 on 2025-12-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0010_historicalcategorieproduit_historicalproduits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduits',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='produits',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
