# Generated by Django 5.2.7 on 2025-12-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0011_historicalproduits_image_url_produits_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduits',
            name='image_url',
            field=models.URLField(max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='image_url',
            field=models.URLField(max_length=190, null=True),
        ),
    ]
