# Generated by Django 5.2.7 on 2025-12-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0011_venteproduit_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venteproduit',
            old_name='Utilisateur',
            new_name='utilisateur',
        ),
    ]
