# Generated by Django 5.2.7 on 2025-12-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0013_alter_historicalproduits_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduits',
            name='image_url',
            field=models.URLField(blank=True, max_length=690, null=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='image_url',
            field=models.URLField(blank=True, max_length=690, null=True),
        ),
    ]
