# Generated by Django 5.2.7 on 2025-12-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0014_alter_historicalproduits_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalventeproduit',
            name='code',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
