# Generated by Django 5.2.7 on 2025-12-30 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0015_alter_historicalventeproduit_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetourVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retour', models.IntegerField(default=0)),
                ('date_retour', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('ligne_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours', to='gestion_produits.lignevente')),
            ],
            options={
                'ordering': ['-date_retour'],
            },
        ),
    ]
