# Generated by Django 5.2.7 on 2025-12-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0016_retourvente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retourvente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venteproduit',
            options={},
        ),
        migrations.AlterField(
            model_name='retourvente',
            name='quantite_retour',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='HistoricalVenteProduit',
        ),
    ]
