# Generated by Django 5.2.7 on 2025-12-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0017_alter_retourvente_options_alter_venteproduit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignevente',
            name='pu_reduction',
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='montant_reduction',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='prix',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='sous_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
