# Generated by Django 5.2.7 on 2025-12-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0018_remove_lignevente_pu_reduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteproduit',
            name='adresseclt_client',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='nom_complet_client',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='telclt_client',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
