# Generated by Django 5.2.7 on 2026-01-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0019_alter_venteproduit_adresseclt_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockproduit',
            name='date_maj',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='stockproduit',
            name='date_maj',
            field=models.DateField(auto_now=True),
        ),
    ]
