# Generated by Django 5.2.7 on 2026-01-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0020_alter_historicalstockproduit_date_maj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteproduit',
            name='total_quanite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
