# Generated by Django 5.2.7 on 2026-01-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produits', '0021_venteproduit_total_quanite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteproduit',
            name='date_vente',
            field=models.DateField(auto_now_add=True),
        ),
    ]
