# Generated by Django 5.2.7 on 2025-12-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_utilisateur',
            field=models.FileField(blank=True, null=True, upload_to='Utilisateur/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('En_Gros', 'En_Gros'), ('En_Details', 'En_Details')], max_length=20),
        ),
    ]
