# Generated by Django 5.2.7 on 2025-12-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0002_alter_utilisateur_photo_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Gerante', 'Gerante')], max_length=20),
        ),
    ]
