# Generated by Django 5.2.7 on 2025-12-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('Gerante', 'Gerante')], max_length=20, null=True),
        ),
    ]
