# Generated by Django 5.2.7 on 2025-12-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0005_historicalutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalutilisateur',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
