# Generated by Django 5.2.7 on 2025-12-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0006_historicalutilisateur_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalutilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('Gerante', 'Gerante'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('Gerante', 'Gerante'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
