# Generated by Django 5.2.7 on 2025-11-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomfour', models.CharField(max_length=40)),
                ('prenomfour', models.CharField(max_length=60)),
                ('adressefour', models.CharField(max_length=60)),
                ('telfour', models.CharField(max_length=25)),
                ('emailfour', models.EmailField(max_length=70)),
                ('photofour', models.ImageField(blank=True, null=True, upload_to='Fournisseurs/')),
                ('date_saisie', models.DateField(auto_now=True)),
            ],
            options={
                'unique_together': {('nomfour', 'prenomfour')},
            },
        ),
    ]
