# Generated by Django 5.2.7 on 2025-11-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseurs',
            name='emailfour',
            field=models.EmailField(max_length=70, null=True),
        ),
    ]
