# Generated by Django 5.2.7 on 2025-12-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_fournisseurs', '0002_alter_fournisseurs_emailfour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseurs',
            old_name='nomfour',
            new_name='nomcomplets',
        ),
        migrations.AlterUniqueTogether(
            name='fournisseurs',
            unique_together={('nomcomplets', 'telfour')},
        ),
        migrations.AlterField(
            model_name='fournisseurs',
            name='adressefour',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='fournisseurs',
            name='photofour',
        ),
        migrations.RemoveField(
            model_name='fournisseurs',
            name='prenomfour',
        ),
    ]
